GET http://localhost:3000/ HTTP/1.1
###
GET http://localhost:3000/test HTTP/1.1
###
GET http://localhost:3000/category HTTP/1.1
### 
POST http://localhost:3000/category HTTP/1.1
content-type: application/json

{
    "name": "No Recomendable"
}
###
GET https://prisma-mongo-test-deploy-production.up.railway.app/food HTTP/1.1
###
POST https://prisma-mongo-test-deploy-budvu0a7y-chelosky.vercel.app/food HTTP/1.1
content-type: application/json

{
    "name": "alimento 6",
    "description": "descripcion generica 5",
    "isEdible": "NO",
    "categoryName": "No Recomendable"
}